# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 063d1fde526946bc6700c5c6f6817826114b68393c3ae3e5f799752797eb564a4a826fe557e5f5416a05c8c7a26245c9aac65d9855c99466b443767d27c9c3d0

test:
  secret_key_base: 8352fe9a5e4c6ad9c4626fdc943b9422a2df50612608bd46507488cfe2e1546984d545da703783240cfc919021b97b19bb334be82b100b521cd806e78478c889

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
